basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='product_all'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('category/<slug:category_slug>/', views.category_list, name='category_list'),
]

basket/models.py
from django.db import models

# Create your models here.

store/models.py
from decimal import Decimal

from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models.signals import post_delete, post_save, pre_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify


# Product Filtering
class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


# Categories Table
class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)
    icon = models.FileField(upload_to='icons/')
    
    class Meta:
        verbose_name_plural = 'categories'
    
    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name
    
# Product Table
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_creator')
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/default.png')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    num_stock = models.PositiveIntegerField(validators=[MaxValueValidator(500)], default=0)
    discount = models.PositiveIntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()
    days_in_stock = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def formatted_price(self):
        return '{:,.2f}'.format(self.price)

    def __str__(self):
        return f'{self.name} - Price: {self.formatted_price()}'
    
    def discounted_price(self):
        discount_percentage = Decimal(self.discount) / 100
        discounted_price = self.price * (1 - discount_percentage)
        
        formatted_price = '{:,.2f}'.format(discounted_price)
        
        return formatted_price


    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        if self.created:
            self.days_in_stock = (timezone.now() - self.created).days
        super(Product, self).save(*args, **kwargs)

def update_days_in_stock(sender, instance, **kwargs):
    if instance.created and instance.is_active:
        instance.days_in_stock = (timezone.now() - instance.created).days
    else:
        instance.days_in_stock = 0

pre_save.connect(update_days_in_stock, sender=Product)

basket/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render

from store.models import Product
from .basket import Basket     

def basket_summary(request):
    basket = Basket(request)
    return render(request, 'store/basket/summary.html', {'basket': basket})


def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product, qty=product_qty)
        
        basketqty = basket.__len__()
        response = JsonResponse({'qty':basketqty})
        return response
    
def basket_delete(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        basket.delete(product=product_id)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response
    
def basket_update(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        basket.update(product=product_id, qty=product_qty)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response

store/views.py
from django.db.models import Count
from django.shortcuts import get_object_or_404, render

from .models import Category, Product


def product_all(request):
    products = Product.products.all()
    product_count = products.count()
    product_category = Category.objects.annotate(num_products=Count('product'))

    return render(request, 'store/home.html', {
        'products': products,
        'product_count': product_count,
        'product_category': product_category
    })


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/products/detail.html', {'product': product})


def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/products/category.html', {'category': category, 'products': products})

templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap');

    * {
        font-family: 'Poppins', sans-serif;
    }

    .errorlist li {
        list-style-type: none;
    }
</style>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Farmstock Davao | {% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'logo.svg' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img src="{% static 'farmstock.svg' %}" alt="logo">
            </a>
            <form class="d-flex">
                <input style="padding: 8px; width: 280px; " class="border border-warning" type="search" placeholder="What are you looking for?" aria-label="Search">
                <button style="border-radius: 0 5px 5px 0;" class="btn btn-warning" type="submit">
                    <img src="{% static 'search.svg' %}" alt="">
                </button>
            </form>
                <div class="d-flex" style="gap:24px;">
                    <a class="align-self-center me-3 position-relative" href="{% url "basket:basket_summary" %}" type="button" role="button"><img src="{% static 'cart.svg' %}" alt="">
                        {% with total_qty=basket|length %}
                            <span id="basket-qty" class="position-absolute translate-middle badge rounded-pill bg-danger">
                            {% if total_qty > 0 %}
                                {{ total_qty }}
                                {% else %}
                                0
                                {% endif %}
                            </span>
                        {% endwith %}
                    </a>
                    <button style="width: 120px; height: 40px;" class="btn btn-warning text-white">Sign In</button>
                </div>
            </div>
            </div>
    </nav>
    <nav class="container navbar navbar-expand-lg navbar-light bg-white">
        <div>
            <ul class="navbar-nav fs-6" style="gap: 32px;">
                <li class="nav-item">
                    <div class="dropdown">
                        <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                            <img style="width: 24px;" class="me-3" src="{% static 'view-list-large2.svg' %}" alt="">
                            All Categories
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            {% for c in categories %}
                            <li>
                                <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title}}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link active text-dark" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="#">Newly Arrived</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="#">Hot Deals</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="#">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="#">Contact Us</a>
                </li>
            </ul>
        </div>
    </nav>
    <hr class="mb-0" style="opacity: 10%;" >

    <div>
        {% block content %}{% endblock %}
    </div>

    <footer class="footer mt-5">
        <div class="bg-warning bg-opacity-25">
            <div class="container d-flex py-5" style="gap:64px;">
                <div>
                    <img src="{% static 'farmstock.svg' %}" alt="logo">
                    <p class="fs-6 ms-2">Purok 10, Libby Road , Talomo District,<br>Davao City, Philippines, 8000</p>
                    <div class="d-flex align-items-center ms-2" style="gap: 16px;">
                        <a href=""><img src="{% static 'socmed1.svg' %}" alt=""></a>
                        <a href=""><img src="{% static 'socmed2.svg' %}" alt=""></a>
                        <a href=""><img src="{% static 'socmed3.svg' %}" alt=""></a>
                        <a href=""><img src="{% static 'socmed4.svg' %}" alt=""></a>
                    </div>
                </div>
                <div class="d-flex flex-column">
                    <h3 class="fs-4 mt-1 pb-2">Categories</h3>
                    <a href="" class="text-body pb-2" style="text-decoration: none;">Pigs</a>
                    <a href="" class="text-body pb-2" style="text-decoration: none;">Cattles</a>
                    <a href="" class="text-body pb-2" style="text-decoration: none;">Goats</a>
                    <a href="" class="text-body pb-2" style="text-decoration: none;">Sheeps</a>
                    <a href="" class="text-body pb-2" style="text-decoration: none;">Ducks</a>
                    <a href="" class="text-body pb-2" style="text-decoration: none;">Others</a>
                </div>
                <div class="d-flex flex-column flex-grow-1">
                    <h3 class="fs-4 mt-1 pb-2">Help Centre</h3>
                    <a href="" class="text-body pb-2" style="text-decoration: none;">About</a>
                    <a href="" class="text-body pb-2" style="text-decoration: none;">Contact</a>
                    <a href="" class="text-body pb-2" style="text-decoration: none;">Pricing & Tax</a>
                    <a href="" class="text-body pb-2" style="text-decoration: none;">Return Policy</a>
                    <a href="" class="text-body pb-2" style="text-decoration: none;">Discount</a>
                </div>
                <div class="d-flex flex-column flex-fill">
                    <h3 class="fs-4 mt-1">Newsletter</h3>
                    <p class="mt-1">Join for more updates and sales  from us!</p>
                    <div class="d-flex">
                        <input class="border border-warning" style="padding: 8px; width: 240px; " type="text" name="" id="" placeholder="example@ymail.com">
                        <button style="border-radius: 0 5px 5px 0; width:100px;" class="btn btn-warning text-white fs-6">Subcribe</button>
                    </div>
                    <div class="d-flex align-items-center my-3">
                        <img src="{% static 'tel.svg' %}" alt="">
                        <p class="m-0 ms-3">+(198)-200-364-215</p>
                    </div>
                    <div class="d-flex align-items-center">
                        <img src="{% static 'mail.svg' %}" alt="">
                        <p class="m-0 ms-3">farmstock_dvo@gmail.com</p>
                    </div>
                </div>
            </div>
        </div>
        <hr class="container my-1">
        <div class="container fs-6 d-flex">
            <span class="flex-grow-1 text-muted">© 2023 Farmstock Davao</span>
            <div>
                <a class="text-body pb-2 px-4" style="text-decoration: none;" href="">Cookies</a>
                <a class="text-body pb-2 px-3" style="text-decoration: none;" href="">Privacy Policy</a>
                <a class="text-body pb-2 ps-3" style="text-decoration: none;" href="">Term of Service</a>
            </div>
        </div>
    </footer>
</body>
</html>

templates/store/basket/summary.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Shopping Basket{% endblock %}

{% block content %}
<main>
    <div class="container py-3">
        <h3 class="fs-2">My Shopping Cart</h3>
        <div>
            <ul class="list-unstyled list-inline mt-4 fs-5 mb-0">
                <li class="list-inline-item" style="margin-right: 350px;">Product Name</li>
                <li class="list-inline-item" style="margin-right: 120px;">Unit Price</li>
                <li class="list-inline-item" style="margin-right: 120px;">Quantity</li>
                <li class="list-inline-item" style="margin-right: 120px;">Total</li>
            </ul>
            <hr class="mt-0">
            
            {% for item in basket %}
            {% with product=item.product %}
            <div data-index="{{product.id}}" class="d-flex flex-row mx-2 my-4 align-items-center position-relative">
                <div class="">
                    <img class="img-thumbnail" width="133px" height="130px" alt="Responsive image" src="{{ product.image.url }}">
                </div>
                <div class="px-3" style="width: 360px;">
                    <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-reset">
                        <h4 class="text-capitalize fs-5">{{ product.name }}</h4>
                    </a>
                </div>
                <div style="width: 215px;">
                    <span class="">₱{{ product.discounted_price }}</span>
                </div>
                <div class="" style="width: 215px;">
                    <p class="m-0">
                        <button class="btn btn-outline-warning rounded text-center p-0" style="height: 30px; width: 30px;" onclick="decreaseQuantity()">-</button>
                        <input style="border: none; width: 20px; text-align: center;" type="text" name="quantity" id="quantity" min="1" max="{{ product.num_stock }}" value="{{ item.qty }}" class="mx-2">
                        <button class="btn btn-outline-warning rounded text-center p-0" style="height: 30px; width: 30px;" onclick="increaseQuantity()">+</button>
                    </p>
                </div>
                <div class="">
                    <div class=""><span class="">₱{{ item.total_price_formatted }}</span></div>
                </div>   
                <div class="position-absolute top-50 start-100 translate-middle">
                    <a href=""><img src="{% static 'close.svg' %}" alt=""></a>
                </div>       
            </div>
            <hr> 
            {% endwith %}
            {% endfor %}
        </div>
        
    </div>
    <div class="bg-light">
        <div class="container">       
            <div class="d-flex justify-content-evenly ms-5" style="gap: 40px;">
                <div class="my-3">
                    <p>Any special instructions for us before checking out?</p>
                    <textarea class="form-control" aria-label="With textarea" placeholder="Type your request here..." style="height: 200px; resize: none;"></textarea>
                </div>
                <div>
                    <div class="d-flex justify-content-between my-3" style="gap: 60px;">
                        <p class="fw-bolder">Items Subtotal:</p>
                        <span id="subtotal" class="d-inline-flex fw-bolder">₱{{basket.get_total_price}}</span>
                    </div>
                    <div>
                        <button class="button btn-lg bg-warning fs-5 text-white" style="border: none; width: 100%;">Proceed to Checkout</button>
                    </div>
                    <hr>
                    <div>
                        <div class="row">
                            <p>Payment Methods</p>
                            <div class="col">
                                <button type="button" class="btn btn-outline-secondary"><img style="height: 30px;" src="{% static 'gcash.svg' %}" alt=""></button>
                                <button type="button" class="btn btn-outline-secondary"><img style="height: 30px;" src="{% static 'paypal.svg' %}" alt=""></button>                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>         
</main>

<script>
    function increaseQuantity() {
        var quantityInput = document.getElementById("quantity");
        var maxStock = parseInt(quantityInput.getAttribute("max"));
        var currentValue = parseInt(quantityInput.value);
        if (currentValue < maxStock) {
            quantityInput.value = currentValue + 1;
        }
    }

    function decreaseQuantity() {
        var quantityInput = document.getElementById("quantity");
        var currentValue = parseInt(quantityInput.value);
        if (currentValue > 1) {
            quantityInput.value = currentValue - 1;
        }
    }

    
</script>

{% endblock %}

templates/store/products/category.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Categories {% endblock %}

{% block content %}
<div class="album pt-3 bg-white">
    <div class="container">
        <h2 class="text-warning py-3">{{ category.name|title }} <span class="text-body">Product</span></h2>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-4">
            
        {% for product in products|slice:":5" %}

        <div class="col">
            <div>
                <a class="position-relative" href="{{ product.get_absolute_url }}">
                    <img class="img-fluid img-thumbnail" alt="Responsive image" style="width: 250px; height: 200px;" src="{{ product.image.url }}">
                    {% if product.discount >= 1 %}
                    <img class="position-absolute opacity-75" style="top: -75px; left: 10px;" src="{% static 'discount.svg' %}" alt="">
                    <img class="position-absolute" style="top: -74px; right: 10px;" src="{% static 'new.svg' %}" alt="">
                    <span class="position-absolute text-white" style="top: -69px; left: 26px; font-size: 8px;">{{product.discount}}%</span>
                    {% endif %}
                </a>
                <div class="d-flex m-1 justify-content-between position-relative">
                    <div class="py-1">
                        <p class="fs-6 m-0 text-truncate"  style="max-width: 200px; white-space: nowrap; overflow: hidden;">{{ product.name }}</p>
                        {% if product.num_stock <= 5 %}
                        <span class="text-danger opacity-75" style="font-size: 12px;">Limited Stock</span>
                        {% else %}
                        <span class="text-success opacity-75" style="font-size: 12px;">In Stock: {{product.num_stock}}</span>
                        {% endif %}
                        <p class="text-decoration-line-through m-0 text-muted" style="font-size: 13px;">₱{{ product.formatted_price }}</p>
                        <p class="fs-6 m-0">₱{{ product.formatted_discounted_price }}</p>
                    </div>
                    <div class="position-absolute bottom-0 end-0">
                        <a class="align-self-end" href="">
                            <img src="{% static 'add.svg' %}" alt="">
                        </a>
                    </div>
                </div>
            </div>
        </div>

    {% endfor %}

    </div>
</div>
{% endblock %}

templates/store/products/detail.html
{% extends "../base.html" %}
{% load static %}
{% block title %}{{ product.name}}{% endblock %}

{% block content %}
<div class="container">
    <div>
        <div class="my-3 mx-2">
            <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
            <ol class="breadcrumb text-decoration-none">
            <li class="breadcrumb-item"><a class="text-decoration-none text-body" href="/">Home</a></li>
            <li class="breadcrumb-item"><a class="text-decoration-none text-body" href="/search/{{ product.category|lower }}">{{ product.category }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ product.name }}</li>
            </ol>
            </nav>
        </div>

        <div class="my-3 mx-2 bg-light rounded container d-flex flex-row">
            <div class="d-flex flex-column" style="height: 93%;">
                <div class="ps-2 pt-3">
                    <img class="img-thumbnail" style="width: 430px; height: 350px;" src="{{ product.image.url }}" alt="">
                </div>
                <div class="d-flex my-1 p-2" style="gap: 10px;">
                    <img class="img-thumbnail" style="width: 100px; height: 100px;" src="{{ product.image.url }}" alt="">
                    <img class="img-thumbnail" style="width: 100px; height: 100px;" src="{{ product.image.url }}" alt="">
                    <img class="img-thumbnail" style="width: 100px; height: 100px;" src="{{ product.image.url }}" alt="">
                    <img class="img-thumbnail" style="width: 100px; height: 100px;" src="{{ product.image.url }}" alt="">
                </div>
            </div>
            <div class="">
                <div class="card m-3" style="width: 600px; height: 93%;">
                    <div class="card-body">
                        <p class="text-success text-capitalize fs-5 m-0">{{ product.name }}</p>
                        <p class="text-body" style="font-size: 14px;">{{ product.created_by }}</p>
                        <p class="fs-4 m-0 text-warning fw-bolder">₱{{ product.discounted_price }}</p>
                        <span class="text-muted text-decoration-line-through">₱{{ product.formatted_price }}</span>
                        {% if product.discount != 0 %}
                            <span>{{ product.discount }}% off</span>
                        {% endif %}
                        <hr>
                        <div class="row" style="gap: 24px; width: 100%;">
                            <p class="col text-muted">Product Description</p>
                            <p class="col">{{ product.description }}</p>
                        </div>
                        <div class="row" style="gap: 24px; width: 100%;">
                            <p class="col text-muted">Number of Stock</p>
                            <p class="col">{{ product.num_stock }} available</p>
                        </div>
                        <div class="row" style="gap: 24px; width: 100%;">
                            <p class="col text-muted">Quantity</p>
                            <p class="col">
                                <button class="btn btn-outline-warning rounded text-center p-0" style="height: 30px; width: 30px;" onclick="decreaseQuantity()">-</button>
                                <input style="border: none; width: 20px; text-align: center;" type="text" name="quantity" id="quantity" min="1" max="{{ product.num_stock }}" value="1" class="mx-2">
                                <button class="btn btn-outline-warning rounded text-center p-0" style="height: 30px; width: 30px;" onclick="increaseQuantity()">+</button>
                            </p>
                        </div>
                        <div class="text-center">
                            <button id="add-to-cart-button" value="{{ product.id }}" type="button" class="btn btn-light border-2 border-warning text-warning px-5"><img class="" style="height:24px; padding-right: 10px;" src="{% static 'cart.svg' %}" alt=""> Add to Cart</button>
                            <button type="button" class="btn btn-warning btn-lg px-5 text-white" style="font-size: 16px; width: 250px;">Buy Now</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function increaseQuantity() {
        var quantityInput = document.getElementById("quantity");
        var maxStock = parseInt(quantityInput.getAttribute("max"));
        var currentValue = parseInt(quantityInput.value);
        if (currentValue < maxStock) {
            quantityInput.value = currentValue + 1;
        }
    }

    function decreaseQuantity() {
        var quantityInput = document.getElementById("quantity");
        var currentValue = parseInt(quantityInput.value);
        if (currentValue > 1) {
            quantityInput.value = currentValue - 1;
        }
    }

    $(document).on('click', '#add-to-cart-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                productid: $('#add-to-cart-button').val(),
                productqty: $('#quantity').val(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
                document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>


{% endblock %}